name: nestjs-playground

services:
  nestjs_playground_postgres:
    image: postgres:16-alpine
    container_name: postgres_nestjs_playground
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '55432:5432'
    volumes:
      - nestjs_playground_postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_playground_network

volumes:
  nestjs_playground_postgres_data:

networks:
  nestjs_playground_network:
    external: true
